import * as Expression from "../scalar.js";
import type { PredicateAtom } from "./atom.js";
import type { AtomFormula, FalseFormula, PredicateFormula, TrueFormula } from "./formula.js";
export interface RuntimeContext {
    readonly nonNullKeys: ReadonlySet<string>;
    readonly nullKeys: ReadonlySet<string>;
    readonly eqLiterals: ReadonlyMap<string, string>;
    readonly neqLiterals: ReadonlyMap<string, ReadonlySet<string>>;
    readonly sourceNames: ReadonlySet<string>;
    readonly contradiction: boolean;
    readonly unknown: boolean;
}
export declare const trueFormula: () => TrueFormula;
export declare const falseFormula: () => FalseFormula;
export declare const atomFormula: <Atom extends PredicateAtom>(atom: Atom) => AtomFormula<Atom>;
export declare const allFormula: (items: readonly PredicateFormula[]) => PredicateFormula;
export declare const anyFormula: (items: readonly PredicateFormula[]) => PredicateFormula;
export declare const notFormula: (item: PredicateFormula) => PredicateFormula;
export declare const andFormula: (left: PredicateFormula, right: PredicateFormula) => PredicateFormula;
export declare const orFormula: (left: PredicateFormula, right: PredicateFormula) => PredicateFormula;
export declare const analyzeFormula: (formula: PredicateFormula) => RuntimeContext;
export declare const normalizeFormula: (formula: PredicateFormula) => PredicateFormula;
export declare const formulaOfExpression: (value: Expression.Any) => PredicateFormula;
export declare const formulaOfPredicate: (value: boolean | Expression.Any) => PredicateFormula;
export declare const assumeFormulaTrue: (assumptions: PredicateFormula, formula: PredicateFormula) => PredicateFormula;
export declare const assumeFormulaFalse: (assumptions: PredicateFormula, formula: PredicateFormula) => PredicateFormula;
export declare const contradictsFormula: (assumptions: PredicateFormula, formula: PredicateFormula) => boolean;
export declare const impliesFormula: (assumptions: PredicateFormula, formula: PredicateFormula) => boolean;
export declare const guaranteedNonNullKeys: (assumptions: PredicateFormula) => ReadonlySet<string>;
export declare const guaranteedNullKeys: (assumptions: PredicateFormula) => ReadonlySet<string>;
export declare const guaranteedSourceNames: (assumptions: PredicateFormula) => ReadonlySet<string>;
