import type * as Brand from "effect/Brand";
import * as Schema from "effect/Schema";
import type { JsonPrimitive, JsonValue } from "../json/types.js";
export type { JsonPrimitive, JsonValue } from "../json/types.js";
export type LocalDateString = string & Brand.Brand<"LocalDateString">;
export type LocalTimeString = string & Brand.Brand<"LocalTimeString">;
export type OffsetTimeString = string & Brand.Brand<"OffsetTimeString">;
export type LocalDateTimeString = string & Brand.Brand<"LocalDateTimeString">;
export type InstantString = string & Brand.Brand<"InstantString">;
export type YearString = string & Brand.Brand<"YearString">;
export type BigIntString = string & Brand.Brand<"BigIntString">;
export type DecimalString = string & Brand.Brand<"DecimalString">;
export declare const LocalDateStringSchema: Schema.Schema<string & Brand.Brand<"LocalDateString">, string & Brand.Brand<"LocalDateString">, never>;
export declare const LocalTimeStringSchema: Schema.Schema<string & Brand.Brand<"LocalTimeString">, string & Brand.Brand<"LocalTimeString">, never>;
export declare const OffsetTimeStringSchema: Schema.Schema<string & Brand.Brand<"OffsetTimeString">, string & Brand.Brand<"OffsetTimeString">, never>;
export declare const LocalDateTimeStringSchema: Schema.Schema<string & Brand.Brand<"LocalDateTimeString">, string & Brand.Brand<"LocalDateTimeString">, never>;
export declare const InstantStringSchema: Schema.Schema<string & Brand.Brand<"InstantString">, string & Brand.Brand<"InstantString">, never>;
export declare const YearStringSchema: Schema.Schema<string & Brand.Brand<"YearString">, string & Brand.Brand<"YearString">, never>;
export declare const BigIntStringSchema: Schema.Schema<string & Brand.Brand<"BigIntString">, string & Brand.Brand<"BigIntString">, never>;
export declare const DecimalStringSchema: Schema.Schema<string & Brand.Brand<"DecimalString">, string & Brand.Brand<"DecimalString">, never>;
export declare const JsonValueSchema: Schema.Schema<JsonValue>;
export declare const JsonPrimitiveSchema: Schema.Schema<JsonPrimitive>;
